image: docker:git

services:
  - docker:dind

stages:
  - build

before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build-and-publish:
  stage: build
  script:
    - docker build --build-arg GIT_HASH=$CI_BUILD_REF -t $CI_REGISTRY_IMAGE:$CI_BUILD_REF -t $CI_REGISTRY_IMAGE:latest -f Dockerfile .
    - docker push $CI_REGISTRY_IMAGE
  only:
    - master

build-and-publish-dev:
  stage: build
  script:
    - docker build --build-arg GIT_HASH=$CI_BUILD_REF -t $CI_REGISTRY_IMAGE:$CI_BUILD_REF -t $CI_REGISTRY_IMAGE:develop -f Dockerfile .
    - docker push $CI_REGISTRY_IMAGE
  only:
    - develop
