image: golang:alpine

stages:
  - test

before_script:
  - export GO111MODULE=on
  - export PKG_LIST=$(shell go list git.unistra.fr/AOEINT/server/... | grep -v /vendor/)
  - apk add git gcc libc-dev
  - go mod download
  - go get -u golang.org/x/lint/golint

unit_tests:
  stage: test
  script:
    - go test -short ./...

race_detector:
  stage: test
  script:
    - go test -race -short ./...

memory_sanitizer:
  stage: test
  script:
    - go test -msan -short ./...

lint_code:
  stage: test
  script:
    - golint -set_exit_status ./...
