image: golang:latest

stages:
  - test

before_script:
  - export GO111MODULE=on
  - go mod download

unit_tests:
  stage: test
  script:
    - go test -short ./...

race_detector:
  stage: test
  script:
    - go test -race ./...

lint_code:
  stage: test
  script:
    - go get -u golang.org/x/lint/golint
    - golint -set_exit_status ./...

cover:
  stage: test
  script:
    -  go test -cover ./...

errcheck:
  stage: test
  script:
    - go get -u github.com/kisielk/errcheck
    - errcheck ./...
