image: golang:latest

stages:
  - test

before_script:
  - export GO111MODULE=on
  - go mod download
  - go get -u golang.org/x/lint/golint

unit_tests:
  stage: test
  script:
    - go test -short ./...

race_detector:
  stage: test
  script:
    - go test -race -short ./...

lint_code:
  stage: test
  script:
    - golint -set_exit_status ./...
